### ISSUE TITLE
Feature request: Show due date in the search results

### ISSUE THREAD

**Issue by rmorrise** [Trekiros/questcheck#2]
As a playtest applicant, when searching through playtest to apply for, it would be cool if the due date of feedback for the playtest was listed in the search result item for each playtest.

Thanks!

**Comment by Trekiros** [comment]
Added this yesterday, thanks for the feedback!

(it only works for playtests which use the contract template, otherwise I don't have access to the information. And for performance reasons, I can only show it in the detailed playtest info page, not in the search page. At least for now, I'll keep an eye out to see if it's possible to include it without burning my server in the process)
